index:
    path:     /
    defaults: { _controller: MrsuhNewspaperBundle:Default:index }

subscribe:
    path:     /subscribe
    defaults: { _controller: MrsuhNewspaperBundle:Api/Subscribe:subscribe }
    methods: [POST]

subscribe_callback_success:
    path:     /subscribe-callback-success
    defaults: { _controller: MrsuhNewspaperBundle:Subscribe:callbackSuccess }
    methods: [GET]

subscribe_callback_fail:
    path:     /subscribe-callback-fail
    defaults: { _controller: MrsuhNewspaperBundle:Subscribe:callbackFail }
    methods: [GET]