services:
    service.pay:
        class: Mrsuh\NewspaperBundle\Service\PayService
        arguments: ["%pay%", "@router"]
        lazy: true

    service.mail:
        class: Mrsuh\NewspaperBundle\Service\MailService
        arguments: ["@mailer", "%mailer_user%"]
        lazy: true

    model.subscribe:
        class: Mrsuh\NewspaperBundle\Model\SubscribeModel
        arguments: ["@doctrine.orm.entity_manager", "@service.pay", "@service.mail", "@templating", "%newspaper.file_path%", "%mailer_user%"]
        lazy: true